Add sameAsOrigin in AllowedOrigins
IBM-Swift/Kitura-CORS pull request #45
Opened 2020-11-13 12:47 UTC by makleso6

2020-11-14 07:46 UTC, mbarnach approved these changes
Looks good to me!

2020-11-15 01:39 UTC, dannys42 requested changes
Would you mind updating the README to include this new parameter as well?

2020-11-15 01:39 UTC, dannys42 commented on Tests/KituraCORSTests/TestCORSOptions.swift
> +                guard (response != nil) else {
Why not something like this?

```
guard let response = response else {
    XCTFail("Missing response")
    return
}
```

2020-11-15 01:39 UTC, dannys42 commented on Tests/KituraCORSTests/TestCORSOptions.swift
> +        performServerTest(router) { expectation in
FYI, I like to set variables at the top of my tests like this:

```
let inputValue = "http://api.bob.com"
let expectedValue = inputValue
var resolvedValue: String
```

In this case, when doing comparison values, such as:

```
XCTAssertEqual(resolvedValue, expectedValue, "reason")
```

It just gives a little more context as to what is expected of the test.

2020-11-15 12:42 UTC, makleso6 commented
@dannys42 I made changes

2020-11-17 04:32 UTC, dannys42 approved these changes
Looks good, thanks!

2020-11-17 04:33 UTC, dannys42 commented
Looks like some errors with the tests.  I'm rerunning them to see if the problem goes away.

2020-11-17 08:06 UTC, mbarnach commented
Looks good now. We can merge! Thanks @makleso6 !

2020-11-18 19:06 UTC, merged